# Generated by Django 4.2.2 on 2023-06-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('editado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ganado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateTimeField()),
                ('numeroMarca', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('foto', models.CharField(max_length=300)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('editado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LitrosDeLeche',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.BigIntegerField()),
                ('vrUnitario', models.BigIntegerField()),
                ('descripcion', models.CharField(max_length=250)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('editado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('raza', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('editado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
